= SQL as REST-Server
:app_name: SQLasRestServer

{app_name} is a lightweight data access layer to SQL databases for HTTP clients.

== Setup

Start a {app_name} application by following these steps:

=== Getting the sources

Clone this repository in addition to https://github.com/fmohr/AILibs[AILibs].
[source, bash]
----
>> git clone https://github.com/fmohr/AILibs.git
>> git clone https://github.com/mwever/SQLasRESTServer.git
>> cd SQLasRESTServer
----

=== Configuration

Supplement a configuration to the application by creating `conf/server.properties` :

[source, properties]
----
# conf/server.properties
db.host = example.com # <1>
db.backend.name = database_name # <2>
db.backend.user = user_name # <3>
db.backend.passwd = password_123 # <4>
server.adapter.instances = 1 # <5>

db.prop.useSSL = true

# Should access to the adapters be limited to `accessLimit` amount.
server.adapter.accessLimited=false
# How many threads can access adapters of a single database at once.
server.adapter.accessLimit=100
# Should the access to the adapters be by random, or by round robin.
server.adapter.randomAccess=true

# Query Logging

server.logging.logSlowQueries = true <6>
server.logging.slowQueryThreshold = 3000 <7>
server.logging.dynamicSlowQueryThreshold = true <8>
server.logging.dynamicSlowQueryThresholdMinLimit = 500 <9>
server.logging.slowestQueriesQuantile = 0.995 <10>

# Performance options used in database connections and their default value:
#db.prop.useCompression = false
#db.prop.defaultFetchSize = 0
#db.prop.useServerPrepStmts = false
#db.prop.cachePrepStmts = false
#db.prop.cachePrepStmtSize = 25
#db.prop.cachePrepStmtSqlLimit = 128
#db.prop.useReadAheadInput = false
#db.prop.cacheServerConf = false
#db.prop.useUnbufferedInput = true
----
<1> The host of the (remote) database server.
<2> The name of the database to connect to.
<3> The username used for authentication.
<4> The password used for authentication.
<5> Number of connections to the database. A higher amount causes more overhead contention but allows for parallel access.
<6> Slow queries will be logged into the admin database. The `Querylogs` table has to be present.
<7> Queries slower than this threshold (milli seconds) will be logged.
<8> If true the threshold will be dynamically lowered in order to capture the slowest quantile of requests.
<9> The dynamic threshold will not be lower than this amount.
<10> The quantile of queries that are logged if dynamic threshold is enabled.


=== Startup

Either start a local server using `.gradlew bootRun`.

Or deploy using docker:

. Build the application. 
This assumes that the docker deamon is running and accessible  from the commandline.
+
----
>> bash build.sh
----
+ 
The resulting docker image is tagged `ai-libs/sql-rest-server`.
+
At this stage, the server configuration is copied from `conf/server.properties` into the docker image.
So after making any changes to the `conf/server.properties` file, make sure to redo this step.

. Start the application.
+
----
>> bash run.sh
----
+ 
This starts a container with named `sqlrest` running the SQLasRESTServer on port 8080.
To change to another port, edit `run.sh` before executing it and replace `-p 8080:8080` with `-p desiredport:8080`.
+
The application will check its connection to the database defined in `conf/server.properties` and fail if unsuccessful.
Check the logs of the server to make sure this doesn't happen: `docker logs sqlrest`

. Stop the application.
+
----
>> bash stop.sh
----

=== Logging table

The server is capable of logging slow requests.
To do so, enable the option in `conf/server.properties`:

----
server.logging.logSlowQueries = true
----

Also, create a table in the admin database called Querylogs:

[source]
----
DROP TABLE IF EXISTS `Querylogs`;

CREATE TABLE `Querylogs` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `session_id` BIGINT NOT NULL,
    `log_reason` text NOT NULL,
    `token` text NOT NULL,
    `sql_query` text NOT NULL,
    `query_start_time` timestamp NOT NULL,
    `query_execution_time` BIGINT,
    `query_threshold` BIGINT,
    `num_current_db_connections` int NOT NULL,
    `num_current_db_token_connections` int NOT NULL,
    `num_requests_since_query` int,
    `num_unfinished_requests_since_query` int,
    `num_jvm_threads` int NOT NULL,
    `used_jvm_memory` BIGINT NOT NULL,
    `free_jvm_memory` BIGINT NOT NULL,
    PRIMARY KEY (`id`)
);
----

=== Query runtime

By default, the service records the time it takes to execute queries.
After the service has served some requests, `/runtime` will return information about average query runtime.

For example, after serving 29181 requests,  `localhost:8080/runtime` might respond with:
[source]
----
{
    "0.005": 2.0,
    "0.01": 3.0, <1>
    "0.1": 28.982330377916117,
    "0.25": 64.98681926316468,
    "0.5": 124.2131860315074, <2>
    "0.75": 178.8774166718975,
    "0.9": 219.68377758164164,
    "0.99": 554.1196257142961, <3>
    "0.995": 1153.10451593136,
    "samples": 29181 <4>

}
----
<1> The fastest one percent of queries take at most 3 milliseconds.
<2> An average query takes 124 milliseconds.
<3> The slowest one percent of queries take at least 554 milliseconds.
<4> The amount of queries served by the service.
