= SQL as REST-Server
:app_name: SQLasRestServer

{app_name} is a lightweight data access layer to SQL databases for HTTP clients.

== Setup

Start a {app_name} application by following these steps:

=== Getting the sources

Clone this repository in addition to https://github.com/fmohr/AILibs[AILibs].
[source, bash]
----
>> git clone https://github.com/fmohr/AILibs.git
>> git clone https://github.com/mwever/SQLasRESTServer.git
>> cd SQLasRESTServer
----

=== Configuration

Supplement a configuration to the application by creating `conf/server.properties` :

[source, properties]
----
# conf/server.properties
db.host = example.com # <1>
db.backend.name = database_name # <2>
db.backend.user = user_name # <3>
db.backend.passwd = password_123 # <4>
server.adapter.instances = 1 # <5>

db.prop.useSSL = true

# Should access to the adapters be limited to `accessLimit` amount.
server.adapter.accessLimited=false
# How many threads can access adapters of a single database at once.
server.adapter.accessLimit=100
# Should the access to the adapters be by random, or by round robin.
server.adapter.randomAccess=true

# Query Logging

server.logging.logSlowQueries = true <6>
server.logging.slowQueryThreshold = 3000 <7>
server.logging.dynamicSlowQueryThreshold = true <8>
server.logging.dynamicSlowQueryThresholdMinLimit = 500 <9>
server.logging.slowestQueriesQuantile = 0.995 <10>

# Performance options used in database connections and their default value:
#db.prop.useCompression = false
#db.prop.defaultFetchSize = 0
#db.prop.useServerPrepStmts = false
#db.prop.cachePrepStmts = false
#db.prop.cachePrepStmtSize = 25
#db.prop.cachePrepStmtSqlLimit = 128
#db.prop.useReadAheadInput = false
#db.prop.cacheServerConf = false
#db.prop.useUnbufferedInput = true
----
<1> The host of the (remote) database server.
<2> The name of the database to connect to.
<3> The username used for authentication.
<4> The password used for authentication.
<5> Number of connections to the database. A higher amount causes more overhead contention but allows for parallel access.
<6> Slow queries will be logged into the admin database. The `Querylogs` table has to be present.
<7> Queries slower than this threshold (milli seconds) will be logged.
<8> If true the threshold will be dynamically lowered in order to capture the slowest quantile of requests.
<9> The dynamic threshold will not be lower than this amount.
<10> The quantile of queries that are logged if dynamic threshold is enabled.


=== Startup

Either start a local server using `.gradlew bootRun`.

Or deploy using docker:

. Build the application. 
This assumes that the docker deamon is running and accessible  from the commandline.
+
----
>> bash build.sh
----
+ 
The resulting docker image is tagged `ai-libs/sql-rest-server`.

. Start the application.
+
----
>> bash run.sh
----
+ 
This starts a container with named `sqlrest`.

. Stop the application.
+
----
>> bash stop.sh
----

=== Logging table

If logging needs to be enabled create a table in the admin database called Querylogs:

[source]
----
include::src/main/resources/create_logging_table.sql[]
----